FROM node:20.12.2-buster

# 作業ディレクトリを設定
WORKDIR /usr/src/app

# 修正している資材のソースコードをコピー
COPY ../../source/app .

# 依存関係をインストール
RUN npm install

# 文字コードに関する色々な環境変数を設定
ENV LANG=ja_JP.UTF-8 \
    LC_CTYPE=ja_JP.UTF-8 \
    LC_NUMERIC=ja_JP.UTF-8 \
    LC_TIME=ja_JP.UTF-8 \
    LC_COLLATE=ja_JP.UTF-8 \
    LC_MONETARY=ja_JP.UTF-8 \
    LC_MESSAGES=ja_JP.UTF-8 \
    LC_PAPER=ja_JP.UTF-8 \
    LC_NAME=ja_JP.UTF-8 \
    LC_ADDRESS=ja_JP.UTF-8 \
    LC_TELEPHONE=ja_JP.UTF-8 \
    LC_MEASUREMENT=ja_JP.UTF-8 \
    LC_IDENTIFICATION=ja_JP.UTF-8 \
    LC_ALL=

# viteのデフォルトのローカルサーバー起動コマンド
CMD ["npm", "run", "dev"]