services:
  db:
    container_name: mira-knowledge-db
    build:
      context: ../
      dockerfile: ./docker/db/Dockerfile
    restart: always
    networks:
      - mira-knowledge-network
    ports:
      - 3316:3306
      - 33160:33060
    env_file:
      - ./.env
    volumes:
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - mysql-datas:/var/lib/mysql
      - mysql-logs:/var/log/mysql

  web:
    container_name: mira-knowledge-web
    build:
      context: ../
      dockerfile: ./docker/web/Dockerfile
    restart: always
    networks:
      - mira-knowledge-network
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./web/default.conf:/etc/nginx/conf.d/default.conf

  api:
    container_name: mira-knowledge-api
    build:
      context: ../
      dockerfile: ./docker/api/Dockerfile
    restart: always
    tty: true
    depends_on:
      - db
      - web
    networks:
      - mira-knowledge-network
    env_file:
      - ./.env
    volumes:
      - ../source/api:/home/gradle/src

  app:
    container_name: mira-knowledge-app
    build:
      context: ../
      dockerfile: ./docker/app/Dockerfile
    restart: always
    tty: true
    depends_on:
      - web
    networks:
      - mira-knowledge-network
    env_file:
      - ./.env
    volumes:
      - ../source/app:/usr/src/app

networks:
  mira-knowledge-network:

volumes:
  mysql-datas:
  mysql-logs:
