version: "3.8"

services:
  db:
    container_name: mira-knowledge-db
    build:
      context: ../
      dockerfile: ./docker/db/Dockerfile
    restart: always
    networks:
      - mira-knowledge-network
    ports:
      - "3316:3306" # ホストのポート3316をコンテナのポート3306にマッピング
      - "33160:33060" # ホストのポート33160をコンテナのポート33060にマッピング
    env_file:
      - ./.env.production
    volumes:
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - mysql-datas:/var/lib/mysql
      - mysql-logs:/var/log/mysql

  web:
    container_name: mira-knowledge-web
    build:
      context: ../
      dockerfile: ./docker/web/Dockerfile
      args:
        - NGINX_CONF=default.prod.conf
    restart: always
    networks:
      - mira-knowledge-network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - app_data:/usr/share/nginx/html

  api:
    container_name: mira-knowledge-api
    build:
      context: ../
      dockerfile: ./docker/api/Dockerfile.prod
    restart: always
    depends_on:
      - db
    networks:
      - mira-knowledge-network
    env_file:
      - ./.env.production
    ports:
      - "8080:8080" # ポート8080を公開

  app:
    container_name: mira-knowledge-app
    build:
      context: ../
      dockerfile: ./docker/app/Dockerfile.prod
    restart: always
    depends_on:
      - web
    networks:
      - mira-knowledge-network
    env_file:
      - ./.env.production
    volumes:
      - app_data:/usr/share/nginx/html
    command: >
      sh -c "npm install && npm run build && cp -r /usr/src/app/dist/* /usr/share/nginx/html"

networks:
  mira-knowledge-network:
    driver: bridge

volumes:
  app_data:
    driver: local
  mysql-datas:
  mysql-logs:
